atoms: fix Atom.h build with Clang
Clang (at least version 3.8.1 on Debian Stretch) fails to compile Atom.h
complaining about Handle construction in various places, like:

In file included from
/home/rik/dev/atomspace/opencog/atoms/base/ClassServer.cc:36:
/home/rik/dev/atomspace/opencog/atoms/base/Atom.h:333:29: error: no matching
conversion for functional-style cast from 'const LinkPtr' (aka 'const
shared_ptr<opencog::Link>') to 'opencog::Handle'
            if ((data->*cb)(Handle(lp))) return true;
                            ^~~~~~~~~
/home/rik/dev/atomspace/opencog/atoms/base/Handle.h:63:7: note: candidate
constructor (the implicit copy constructor) not viable: no known conversion
from 'const LinkPtr' (aka 'const shared_ptr<opencog::Link>') to 'const
opencog::Handle' for 1st argument
class Handle : public AtomPtr
      ^
/home/rik/dev/atomspace/opencog/atoms/base/Handle.h:80:14: note: candidate
constructor not viable: no known conversion from 'const
shared_ptr<opencog::Link>' to 'const shared_ptr<opencog::Atom>' for 1st
argument
    explicit Handle(const AtomPtr& atom) : AtomPtr(atom) {}
             ^
/home/rik/dev/atomspace/opencog/atoms/base/Handle.h:81:14: note: candidate
constructor not viable: requires 0 arguments, but 1 was provided
    explicit Handle() {}
             ^
1 error generated.

Not sure whether it's a proper behaviour on Clang's side but a little
static_pointer_casting helps it so it probably also won't hurt GCC.