guile: add missing attribute to throw_exception() of SchemeSmob
Clang fails to compile it complaining about attribute mismatch between
declaration and implementation:

opencog/guile/SchemeSmob.cc:156:4: error: function declared '[[noreturn]]'
after its first declaration
[[ noreturn ]] void SchemeSmob::throw_exception(const std::exception& ex,
   ^
/home/rik/dev/atomspace/opencog/guile/SchemeSmob.h:212:14: note: declaration
missing '[[noreturn]]' attribute is here
        static void throw_exception(const std::exception&, const char *, SCM);